In [3]:
import numpy as np

In [2]:
a = np.array([1, 2, 3, 4, 5])

In [3]:
print(a)

[1 2 3 4 5]


In [4]:
print(type(a))

<class 'numpy.ndarray'>


In [5]:
print(a.shape) # returns dimensions of the array

(5,)


In [7]:
b = np.array([[1], [2], [3], [4], [5]])

In [8]:
print(b)
print(b.shape)

[[1]
 [2]
 [3]
 [4]
 [5]]
(5, 1)


In [9]:
c = np.array([[1, 2, 3], [4, 5, 6]])
print(c)
print(c.shape)
print(c[1][1])

[[1 2 3]
 [4 5 6]]
(2, 3)
5


In [20]:
# printing arrays of zeroes and ones
a = np.zeros((3, 3))
print(a)

b = np.ones((2, 3))
print(b)

# array of some constants
c = np.full((3, 2), 5)
print(c)

# identity matrix
d = np.eye(3, 3)
print(d)

# random matrix
randomMatrix = np.random.random((2, 3))
print(randomMatrix)

[[ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]
[[ 1.  1.  1.]
 [ 1.  1.  1.]]
[[5 5]
 [5 5]
 [5 5]]
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]
[[ 0.45977774  0.19336065  0.08009018]
 [ 0.8322619   0.28864911  0.19510262]]


In [21]:
print(randomMatrix[ : , 1])

[ 0.19336065  0.28864911]


In [25]:
randomMatrix[1, 1:3] = 1
print(randomMatrix)

[[ 0.45977774  0.19336065  0.08009018]
 [ 0.8322619   1.          1.        ]]


In [26]:
# DATATYPES

In [31]:
z = np.zeros((3, 2))
print(z)
print(z.dtype)

[[ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]]
float64


In [36]:
# Mathematical Operations

x = np.ones((2, 3))
y = np.ones((2, 3))

# print(x+y)
# print(np.add(x, y))

[[ 2.  2.  2.]
 [ 2.  2.  2.]]


In [73]:
# Multiplication of Vectors - Scalar
a = np.array([1, 2, 3, 4])
b = np.array([1, 2, 3, 4])
print(a.dot(b))

30


In [5]:
print(a)

[1 2 3 4]


In [6]:
print(sum(a))

10


In [30]:
x = np.array([[1, 2],[3, 4]])
print(x)

[[1 2]
 [3 4]]


In [32]:
print(np.sum(x))
print(np.sum(x, axis = 0))

10
[4 6]


In [34]:
print(np.sum(x))
print(np.sum(x, axis = 1))

10
[3 7]


In [74]:
# Stacking of Arrays
print(a)
b = b**2
print(b)

[1 2 3 4]
[ 1  4  9 16]


In [75]:
a = np.stack((a,b), axis = 0)

In [76]:
print(a)

[[ 1  2  3  4]
 [ 1  4  9 16]]


In [77]:
a = a.reshape((4, 2))
print(a)

[[ 1  2]
 [ 3  4]
 [ 1  4]
 [ 9 16]]


In [78]:
a = a.reshape((8, 1))
print(a)

[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 1]
 [ 4]
 [ 9]
 [16]]


# Numpy Random Module

* rand: Random value in a given shape
* randn: Return a sample from the standard normal distribution
* randint: Return random integers from low to high
* random: Return random floats in the half-open interval (0.0, 1.0)
* choice: Generates a random sample from a given 1-D array
* Shuffle: Shuffles the contents of a sequence

In [86]:
a = np.array([5, 6, 7, 8, 1, 2, 3, 4])
a = np.arange(10) + 5
print(a)

[ 5  6  7  8  9 10 11 12 13 14]


In [87]:
# Pseudo Random Generator
np.random.seed(1)
np.random.shuffle(a)
print(a)

[ 6 12  7 11  8  5 10 14  9 13]


In [92]:
# Returns values from standard normal distribution
a = np.random.randn(2, 3)
print(a)

a = np.random.randint(5, 10, 3)
print(a)

# Randomly pick one element from an array
element = np.random.choice([1, 4, 3, 2, 11, 6])
print(element)


[[-1.30259797  0.69101683  0.35526523]
 [ 0.75420875  1.6193466   0.57324287]]
[5 8 7]
3


# Some More Numpy Functions - Statistics
* min, max
* mean
* median
* average
* variance
* standard deviation

In [95]:
a = np.array([[1, 2, 3, 4],[7, 6, 2, 0]])

In [99]:
print(a)
print(np.min(a))

# specify axis for multidim array
print(np.min(a, axis = 0))
print(np.min(a, axis = 1))

[[1 2 3 4]
 [7 6 2 0]]
0
[1 2 2 0]
[1 0]


In [101]:
b = np.array([1, 2, 3, 4 , 5])
m = sum(b)/5
print(m)

print(np.mean(b))
print(np.mean(a, axis = 0))
print(np.mean(a, axis = 1))

3.0
3.0
[ 4.   4.   2.5  2. ]
[ 2.5   3.75]


In [105]:
c = np.array([1, 5, 4, 2, 0])
print(np.median(c))

# Mean vs Average is Weighted
print(np.mean(c))

# Weights
w = np.array([1, 1, 1, 1, 1])
print(np.average(c, weights=w))

# Standard Deviation
u = np.mean(c)
sd = np.sqrt(np.mean(abs(c-u)**2))
print(sd)

dev = np.std(c)
print(dev)

print(sd**2)
print(np.var(c))

2.0
2.4
2.4
1.8547236991
1.8547236991
3.44
3.44
